spring:
  application:
    name: spring-ai-intro
  ai:
    model:
      chat: openai # choose between ollama, openai
      embedding: openai # choose between ollama, openai
      image: none # disabled
      audio:
        speech: none # disabled
        transcription: none # disabled
    ollama:
        base-url: http://localhost:11434/
        chat:
          options:
            model: llama3.2
        embedding:
          options:
            model: llama3.2
    openai:
        base-url: https://api.openai.com/
        api-key: ${OPENAI_API_KEY}
        chat:
          options:
            model: gpt-4o
        embedding:
          options:
            model: text-embedding-3-small


