spring:
  application:
    name: spring-ai-intro
  ai:
    model:
      chat: ollama # choose between ollama, openai
      embedding: ollama # choose between ollama, openai
      image: none # disabled
      moderation: none # disabled
      audio:
        speech: none # disabled
        transcription: none # disabled
    ollama: # http://localhost:11434 is default base-url
        chat:
          options:
            model: llama3.2
        embedding:
          options:
            model: llama3.2
